### ISSUE TITLE
Import of InstrumentResponse from threeML is incorrect

### ISSUE THREAD

**Issue by dsvinkin** [grburgess/gbm_drm_gen#12]
Hi all!
The import statement in drmgen.py
`from threeML.utils.response import InstrumentResponse`
should be 
`from threeML.utils.OGIP.response import InstrumentResponse`
to correspond of the current structure of threeML.

**Comment by grburgess** [comment]
thanks! If you would, could you make fork and do a PR? I've also separated the the response stuff out of 3ML to bypass that as a dependency, but this should be fixed.

**Comment by grburgess** [comment]
Thanks for fixing this @dsvinkin
